name: Generate Stats Cards

on:
  schedule:
    - cron: "0 */12 * * *"
  workflow_dispatch: {}
  push:
    branches:
      - main

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Generate stats images (overview + languages)
        uses: jstrieb/github-stats@master
        with:
          username: Collins526
          access_token: ${{ secrets.ACCESS_TOKEN }}
          exclude_repos: ""
          exclude_langs: "HTML"
